name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the latest code
      - uses: actions/checkout@v3

      # Set up Node and cache dependencies
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # Install all dependencies
      - name: Install Dependencies
        run: npm ci

      # Build the Ember application
      - name: Build Ember App
        run: ember build --environment=production

      # Run your Cucumber/Playwright tests
      - name: Run BDD Tests
        run: npm run bdd

      # Configure AWS credentials for deployment
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Staging
        run: aws s3 sync dist/ s3://staging.sambordo.ninja/

      # Your Cucumber steps now point to staging.sambordo.ninja in the code:
      - name: Run BDD Tests Against Staging
        run: npm run bdd

      - name: Deploy to Production
        if: success()
        run: aws s3 sync dist/ s3://sambordo.ninja/ --acl public-read